name: "📜 Documentation builder"
on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # To be able to push refs to destination repo
    - uses: actions/setup-python@v3
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: |
          pip install myst-parser
          pip install myst-nb
        build-command: "sphinx-build -b html . _build -w /tmp/sphinx.log "
    - name: Deploy 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
