name: "📜 Documentation builder"
on: [pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # To be able to push refs to destination repo
    - uses: actions/setup-python@v3
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build -b html docsource/ _build "
        docs-folder: "docs/"
        pre-build-command: |
          pip install myst-parser
          pip install myst-nb
    - name: Deploy 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:

        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build


# fixme - fix this in the workflow, currently  no build maybe look at build-command
#====================================
#Building docs in docs/
#====================================
#[sphinx-action] Running: ['sphinx-build', '-b', 'html', 'docsource/', '_build', '--keep-going', '--no-color', '-w', '/tmp/sphinx-log']
#[sphinx-action] Build succeeded with 0 warnings
